name: Robotics Club Blog
url: https://shashikg.github.io/robotics_club_blog
suburl
paginate: 5
paginate_path: "/blog/page:num/"
plugins: 
- jekyll-paginate

markdown: kramdown

kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false

highlighter: rouge

exclude: ["/docs"]
destination: "/home/shashi/gitrepo/robotics_club_blog/docs/"